image: rocker/tidyverse:3.6.0

stages:
  - build
  - deploy

variables:
  R_LIBS_USER: "$CI_PROJECT_DIR/ci/lib"
  CHECK_DIR: "$CI_PROJECT_DIR/ci/logs"
  BUILD_DIR: "$CI_PROJECT_DIR/ci/build"
  BUILD_LOGS_DIR: "$CI_PROJECT_DIR/ci/logs/$CI_PROJECT_NAME.Rcheck"

checking:
  stage: build
  script:
  - mkdir -p $R_LIBS_USER $BUILD_LOGS_DIR $BUILD_DIR
  - Rscript -e 'devtools::install_deps(dependencies = T, lib = Sys.getenv("R_LIBS_USER"))' \
            -e 'devtools::check(check_dir = Sys.getenv("CHECK_DIR"))' 
  cache:
    paths:
      - $R_LIBS_USER


coverage:
  stage: deploy
  when: on_success
  script:
    - R -e 'covr::package_coverage(type = c("tests", "examples"), quiet = FALSE)'



