stages:
  - build
  - checking
  - testing

variables:
  IMAGE_TAG: dreg.harmonic.co.nz:5000/harmonic/databases/db-censusnz:$CI_PIPELINE_ID

build-docker-container:
  stage: build
  tags:
      - shell
      - dockerbuild
      - wellington
  script:
    - docker build --pull -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

package-check:
  stage: checking
  tags:
      - docker
  image: $IMAGE_TAG
  variables:
    GIT_STRATEGY: none
    KUBERNETES_MEMORY_REQUEST: 6Gi
  script:
    - cd /censusnz
    - R -e 'devtools::check()'

coverage:
  stage: testing
  tags:
      - docker
  image: $IMAGE_TAG
  variables:
    GIT_STRATEGY: none
  script:
    - cd /db.censusnz
    - R -e 'covr::package_coverage(type = c("tests", "examples"), quiet = FALSE)'


